# Generated by Django 5.2.5 on 2025-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_comercial_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_comercial_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_comercial_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_comercial_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_financiero_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_financiero_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_financiero_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_financiero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('representante_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('representante_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('representante_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=30)),
                ('telefono_empresa', models.CharField(max_length=20)),
                ('correo_empresa', models.EmailField(max_length=254)),
                ('entidad_bancaria', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_banco', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad_banco', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pago', models.CharField(choices=[('credito', 'Crédito'), ('contado', 'Contado')], max_length=10)),
                ('cupo_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plazo_credito', models.PositiveIntegerField(blank=True, help_text='Días', null=True)),
                ('rut', models.FileField(blank=True, null=True, upload_to='documentos/rut/')),
                ('certificacion_bancaria', models.FileField(blank=True, null=True, upload_to='documentos/cert_bancaria/')),
                ('camara_comercio', models.FileField(blank=True, null=True, upload_to='documentos/camara_comercio/')),
                ('qr_image', models.ImageField(blank=True, editable=False, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
