# Generated by Django 5.2.5 on 2025-08-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo_empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='representante_cedula',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_cedula_archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cedulas/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=3),
        ),
    ]
